// DO NOT MODIFY
// This file is automatically generated by command 'cargo run xxx'
//
#[rustfmt::skip]
lazy_static! {
    static ref UPPERCASE_AZ: HashMap<u32, Uppercase> = {
        let mut m = HashMap::new();
        m.insert(65, Uppercase {letter: Letter::Letter('A'), property: Property::Capital});
        m
    };
}