/// DO NOT MODIFY
/// This file is automatically generated by command 'cargo run <filename>
///
use lazy_static::lazy_static;

use std::collections::HashMap;
use std::ops::Index;

use crate::letter::Letter;
use crate::property::Property;
use crate::uppercase::{Uppercase, NOT_A_UPPERCASE};

// Construct a Hashmap for uppercase AZ equivalent
#[rustfmt::skip]
lazy_static! {
    static ref UPPERCASE_AZ: HashMap<u32, Uppercase> = {
        let mut m = HashMap::new();
        m.insert(65, Uppercase {letter: Letter::Letter('A'), property: Property::Capital});
        m
    };
}

/// All Uppercase AZ equivalent
#[derive(Debug, Clone)]
pub struct UppercaseAZ<'a>(&'a HashMap<u32, Uppercase>);

impl Default for UppercaseAZ<'_> {
    fn default() -> Self {
        UppercaseAZ(&UPPERCASE_AZ)
    }
}

impl Index<char> for UppercaseAZ<'_> {
    type Output = Uppercase;

    fn index(&self, index: char) -> &Self::Output {
        self.get_ref(index)
    }
}

impl UppercaseAZ<'_> {
    #[must_use]
    pub fn get(&self, c: char) -> Option<Uppercase> {
        let code_point = c as u32;
        self.0.get(&code_point).copied()
    }

    #[must_use]
    pub fn get_ref(&self, c: char) -> &Uppercase {
        let code_point = c as u32;
        self.0
            .get(&code_point)
            .map_or(&NOT_A_UPPERCASE, |uppercase| uppercase)
    }

    #[must_use]
    pub fn get_string(&self, c: char) -> Option<String> {
        let code_point = c as u32;
        self.0
            .get(&code_point)
            .map(|uppercase| uppercase.letter.to_string())
    }

    #[must_use]
    pub fn to_string(&self, c: char) -> String {
        self.get_string(c).map_or_else(|| c.to_string(), |s| s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_uppercase_az_get() {
        let uppercase_az = UppercaseAZ::default();
        assert_eq!(
            uppercase_az.get('A'),
            Some(Uppercase {
                letter: Letter::Letter('A'),
                property: Property::Capital
            })
        );
        assert_eq!(uppercase_az.get_string('A'), Some("A".to_string()));
        assert_eq!(uppercase_az.to_string('A'), "A".to_string());
    }

    #[test]
    fn test_uppercase_az_index() {
        let uppercase_az = UppercaseAZ::default();
        assert_eq!(
            uppercase_az['A'],
            Uppercase {
                letter: Letter::Letter('A'),
                property: Property::Capital
            }
        );
    }

    #[test]
    fn test_uppercase_az_get_nonexistent_letter() {
        let uppercase_az = UppercaseAZ::default();
        assert_eq!(uppercase_az.get('2'), None);
        assert_eq!(uppercase_az.to_string('2'), "2");
    }
}
